name: bookshelf
description: An app to explore books through Google Books Api
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  
  session_mate:
    path: ../
  session_mate_core:
  

  http: ^1.1.0
  freezed_annotation: ^2.4.1
  faker: ^2.1.0
  uuid: ^3.0.7
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.5.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

dependency_overrides:
  session_mate_core:
    path: ../../session_mate_core

flutter:
  uses-material-design: true

